services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: runner
    container_name: chronos-api
    env_file:
      - .env.test.example
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    expose:
      - "4000"
    networks:
      - chronos
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.bun
      target: runner
    container_name: chronos-web
    env_file:
      - .env.test.example
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    expose:
      - "3000"
    networks:
      - chronos
    depends_on:
      - api
    restart: unless-stopped

  proxy:
    image: nginx:1.27-alpine
    container_name: chronos-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - web
      - api
    networks:
      - chronos
    restart: unless-stopped

networks:
  chronos:
    driver: bridge
